### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bdunderscore** [bdunderscore/vrchat-scroll-calendar#1]
- [x] Update README.md
- [x] Tag release
- [x] Generate and attach unity package
- [x] Update template footer in generation package
- [x] Booth upload & publication
- [x] Twitter announcement
